In [ ]:
pip install faker

Collecting faker
  Downloading Faker-28.0.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-28.0.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 32.0 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-28.0.0

In [ ]:
from faker import Faker
import random

# Initialize Faker
fake = Faker()

# Define format settings
phone_format = "+1-###-###-####"
email_domain = "example.com"

# Generate data for Customers table
def generate_customers(num_customers=100):
    customers = []
    for i in range(6, num_customers + 1):
        customers.append({
            "CustomerID": i,
            "Name": fake.name(),
            "Address": fake.address().replace("\n", ", "),
            "Email": f"{fake.user_name()}@{email_domain}",
            "Phone": fake.numerify(phone_format)
        })
    return customers

# Generate data for Suppliers table
def generate_suppliers(num_suppliers=12):
    suppliers = []
    for i in range(6, num_suppliers + 1):
        suppliers.append({
            "SupplierID": i,
            "Name": fake.company(),
            "ContactInfo": f"{fake.user_name()}@{email_domain} | {fake.numerify(phone_format)}",
            "Rating": round(random.uniform(3.0, 5.0), 2)
        })
    return suppliers

# Generate data for Warehouses table
def generate_warehouses(num_warehouses=7):
    warehouses = []
    for i in range(6, num_warehouses + 1):
        warehouses.append({
            "WarehouseID": i,
            "Location": f"{fake.city()}, {fake.state_abbr()}",
            "Capacity": round(random.uniform(5000, 15000), 2)
        })
    return warehouses

# Generate data for Products table
def generate_products(num_products=60, num_suppliers=12):
    products = []
    categories = ['Electronics', 'Machinery', 'Groceries', 'Furniture', 'Hardware']
    for i in range(6, num_products + 1):
        products.append({
            "ProductID": i,
            "Name": f"{fake.word().capitalize()} Model {chr(64 + i)}",
            "Category": random.choice(categories),
            "UnitPrice": round(random.uniform(10, 1000), 2),
            "SupplierID": random.randint(1, num_suppliers)
        })
    return products

# Generate data for Orders table
def generate_orders(num_orders=200, num_customers=100):
    orders = []
    for i in range(6, num_orders + 1):
        orders.append({
            "OrderID": i,
            "CustomerID": random.randint(1, num_customers),
            "OrderDate": fake.date_between(start_date='-1y', end_date='today'),
            "TotalAmount": round(random.uniform(100, 2000), 2)
        })
    return orders

# Generate data for OrderDetails table
def generate_order_details(num_order_details=90, num_orders=190, num_products=60):
    order_details = []
    for i in range(6, num_order_details + 1):
        order_details.append({
            "OrderDetailID": i,
            "OrderID": random.randint(1, num_orders),
            "ProductID": random.randint(1, num_products),
            "Quantity": random.randint(1, 100),
            "Price": round(random.uniform(10, 1000), 2)
        })
    return order_details

# Generate data for Inventory table
def generate_inventory(num_inventory=300, num_products=60, num_warehouses=7):
    inventory = []
    for i in range(6, num_inventory + 1):
        inventory.append({
            "InventoryID": i,
            "ProductID": random.randint(1, num_products),
            "WarehouseID": random.randint(1, num_warehouses),
            "Quantity": random.randint(50, 1000)
        })
    return inventory

# Generate data for Shipments table
def generate_shipments(num_shipments=67, num_orders=200, num_warehouses=7):
    carriers = ['FedEx', 'UPS', 'DHL', 'USPS']
    delivery_statuses = ['Delivered', 'In Transit', 'Pending']
    shipments = []
    for i in range(6, num_shipments + 1):
        shipments.append({
            "ShipmentID": i,
            "OrderID": random.randint(1, num_orders),
            "WarehouseID": random.randint(1, num_warehouses),
            "ShipmentDate": fake.date_between(start_date='-1y', end_date='today'),
            "Carrier": random.choice(carriers),
            "DeliveryStatus": random.choice(delivery_statuses)
        })
    return shipments

# Generate data for SupplierDeliveries table
def generate_supplier_deliveries(num_deliveries=89, num_suppliers=11, num_products=60):
    delivery_statuses = ['Completed', 'Pending']
    supplier_deliveries = []
    for i in range(6, num_deliveries + 1):
        supplier_deliveries.append({
            "DeliveryID": i,
            "SupplierID": random.randint(1, num_suppliers),
            "ProductID": random.randint(1, num_products),
            "DeliveryDate": fake.date_between(start_date='-1y', end_date='today'),
            "Quantity": random.randint(100, 5000),
            "DeliveryStatus": random.choice(delivery_statuses)
        })
    return supplier_deliveries

# Generate and print the data for each table
def print_insert_statements():
    # Customers
    customers = generate_customers()
    print("INSERT INTO Customers (CustomerID, Name, Address, Email, Phone) VALUES")
    for customer in customers:
        print(f"({customer['CustomerID']}, '{customer['Name']}', '{customer['Address']}', '{customer['Email']}', '{customer['Phone']}'),")
    print()

    # Suppliers
    suppliers = generate_suppliers()
    print("INSERT INTO Suppliers (SupplierID, Name, ContactInfo, Rating) VALUES")
    for supplier in suppliers:
        print(f"({supplier['SupplierID']}, '{supplier['Name']}', '{supplier['ContactInfo']}', {supplier['Rating']}),")
    print()

    # Warehouses
    warehouses = generate_warehouses()
    print("INSERT INTO Warehouses (WarehouseID, Location, Capacity) VALUES")
    for warehouse in warehouses:
        print(f"({warehouse['WarehouseID']}, '{warehouse['Location']}', {warehouse['Capacity']}),")
    print()

    # Products
    products = generate_products()
    print("INSERT INTO Products (ProductID, Name, Category, UnitPrice, SupplierID) VALUES")
    for product in products:
        print(f"({product['ProductID']}, '{product['Name']}', '{product['Category']}', {product['UnitPrice']}, {product['SupplierID']}),")
    print()

    # Orders
    orders = generate_orders()
    print("INSERT INTO Orders (OrderID, CustomerID, OrderDate, TotalAmount) VALUES")
    for order in orders:
        print(f"({order['OrderID']}, {order['CustomerID']}, '{order['OrderDate']}', {order['TotalAmount']}),")
    print()

    # OrderDetails
    order_details = generate_order_details()
    print("INSERT INTO OrderDetails (OrderDetailID, OrderID, ProductID, Quantity, Price) VALUES")
    for detail in order_details:
        print(f"({detail['OrderDetailID']}, {detail['OrderID']}, {detail['ProductID']}, {detail['Quantity']}, {detail['Price']}),")
    print()

    # Inventory
    inventory = generate_inventory()
    print("INSERT INTO Inventory (InventoryID, ProductID, WarehouseID, Quantity) VALUES")
    for inv in inventory:
        print(f"({inv['InventoryID']}, {inv['ProductID']}, {inv['WarehouseID']}, {inv['Quantity']}),")
    print()

    # Shipments
    shipments = generate_shipments()
    print("INSERT INTO Shipments (ShipmentID, OrderID, WarehouseID, ShipmentDate, Carrier, DeliveryStatus) VALUES")
    for shipment in shipments:
        print(f"({shipment['ShipmentID']}, {shipment['OrderID']}, {shipment['WarehouseID']}, '{shipment['ShipmentDate']}', '{shipment['Carrier']}', '{shipment['DeliveryStatus']}'),")
    print()

    # SupplierDeliveries
    supplier_deliveries = generate_supplier_deliveries()
    print("INSERT INTO SupplierDeliveries (DeliveryID, SupplierID, ProductID, DeliveryDate, Quantity, DeliveryStatus) VALUES")
    for delivery in supplier_deliveries:
        print(f"({delivery['DeliveryID']}, {delivery['SupplierID']}, {delivery['ProductID']}, '{delivery['DeliveryDate']}', {delivery['Quantity']}, '{delivery['DeliveryStatus']}'),")
    print()

# Execute the function to print the SQL insert statements
print_insert_statements()

INSERT INTO Customers (CustomerID, Name, Address, Email, Phone) VALUES
(6, 'Jennifer Fowler', 'Unit 3788 Box 9394, DPO AE 19985', 'deleonwilliam@example.com', '+1-391-492-4809'),
(7, 'William Lozano', '12821 Pennington Port, Lake Jessicastad, WI 30805', 'wpratt@example.com', '+1-844-187-0410'),
(8, 'Emily Moss', '801 Taylor Rest Apt. 887, Lake Jennifer, AZ 90936', 'rebeccajordan@example.com', '+1-325-405-2245'),
(9, 'Ashley James', '206 Thornton Spur Apt. 188, West Stephanieshire, ME 55877', 'xjackson@example.com', '+1-497-241-9888'),
(10, 'Cindy Vazquez', '762 Webster Road Apt. 637, Millschester, CT 85865', 'linda99@example.com', '+1-921-996-0123'),
(11, 'Brittney Ewing', '241 Carrie Bypass, New Michaelton, CT 69510', 'bbanks@example.com', '+1-322-786-6646'),
(12, 'Tara Spencer', '8462 Alexander Pass Apt. 046, North Amberview, AR 27318', 'ewise@example.com', '+1-225-906-0346'),
(13, 'Mary Hernandez', '31258 Denise Crest, South Joseph, DC 78015', 'pamela96@example.com', '+1-435-722-4366'),
(14, 'Allison Brooks', '81769 Theresa Canyon Apt. 513, Walkerbury, GU 19528', 'nelsondavid@example.com', '+1-092-199-8506'),
(15, 'Brandon Flores', '5891 Troy Valley, Anthonyhaven, CA 66760', 'townsenderic@example.com', '+1-109-078-9538'),
(16, 'Deanna Knox', '314 Connie Forge, East Jennifer, IL 63695', 'benjamin71@example.com', '+1-542-751-2077'),
(17, 'Nancy Ross', 'USNV Stevens, FPO AA 18499', 'pollardnicole@example.com', '+1-302-052-2197'),
(18, 'Bethany Jones', '7681 Jacob Drive Suite 822, Rebeccaland, IN 90681', 'butlerkathryn@example.com', '+1-022-625-0828'),
(19, 'Cynthia Mendez', '27880 Brian Glens Apt. 717, Port David, DE 40424', 'wallacejack@example.com', '+1-033-749-5032'),
(20, 'Steven Harris', '78998 David Row, Allisonborough, SC 15490', 'jeffreycampbell@example.com', '+1-446-985-1593'),
(21, 'Robert Bishop', '3323 Williams Wells Apt. 443, North Lisa, NC 69446', 'bradley43@example.com', '+1-598-139-6732'),
(22, 'Gabrielle Barber', '123 Coleman Union Apt. 968, Lake Benjaminside, NC 99605', 'mmiller@example.com', '+1-102-959-2701'),
(23, 'Charles Daniels', '2450 Duarte Common Apt. 797, Isaacfort, AR 74719', 'melissa08@example.com', '+1-871-547-0559'),
(24, 'Mr. Robert Peterson', '83726 Emma Fort Apt. 443, Port Laurenchester, CT 25950', 'katie03@example.com', '+1-131-633-6100'),
(25, 'Carl Charles', '5284 Barnes Alley Suite 257, Port Dawn, AZ 26776', 'johnosborne@example.com', '+1-649-751-3539'),
(26, 'Margaret King', '085 Kristen Centers Suite 893, Billyberg, MA 37008', 'willieelliott@example.com', '+1-726-895-6114'),
(27, 'Danny Dominguez', '08783 Ronald Views, Stevenview, WY 20209', 'jenniferpeters@example.com', '+1-268-619-8392'),
(28, 'Christina Roth', '8875 Nancy Route Suite 796, North Ashley, CA 02411', 'jweaver@example.com', '+1-121-206-8724'),
(29, 'Paul Washington', '9331 Dominique Radial Suite 957, North Alexander, ME 25646', 'dfoster@example.com', '+1-114-759-7098'),
(30, 'Linda Michael', '6897 Michael Avenue, West Derek, PA 07307', 'daniel71@example.com', '+1-661-526-2143'),
(31, 'Michael Johnson', '9245 Padilla Orchard, Lake Annashire, NY 30367', 'longpatrick@example.com', '+1-268-347-2537'),
(32, 'Joshua Salas', '73458 Mike Plaza Apt. 295, Daviesstad, MI 60267', 'ryan01@example.com', '+1-892-993-1061'),
(33, 'Caitlin Travis', '641 Fuentes Flat Suite 722, Howardtown, MA 18176', 'john74@example.com', '+1-215-513-3726'),
(34, 'Danielle Adams', '925 Jessica Manors Apt. 715, Johnsonfurt, HI 61041', 'castillodanielle@example.com', '+1-421-360-9371'),
(35, 'Bruce Newton', '42420 Edwards Knolls, South Taylor, ND 76109', 'michaelgarcia@example.com', '+1-013-833-6186'),
(36, 'Samantha Scott', '6131 Thomas Curve, Wendytown, TN 76309', 'halllynn@example.com', '+1-256-758-6171'),
(37, 'Robert Williamson', '011 Salazar Hills, Josephberg, OH 10307', 'amandabriggs@example.com', '+1-563-608-8543'),
(38, 'Shane Freeman', '901 Nguyen Alley, Port Sara, CT 41197', 'crystal32@example.com', '+1-072-823-5344'),
(39, 'Deborah Vazquez', '59113 Gay Skyway, Thomasfurt, UT 37559', 'johnsonmichael@example.com', '+1-863-332-9129'),
(40, 'Jessica Moreno', '93620 Julie Plain Suite 670, Leside, WA 35885', 'jeffrey77@example.com', '+1-563-490-2543'),
(41, 'Brett White', '14371 Rachel Squares, Port Lisa, ND 12251', 'ruth84@example.com', '+1-319-451-1008'),
(42, 'Jonathon Gonzalez', '28848 Martinez Inlet, Susanfort, AK 16035', 'javiercowan@example.com', '+1-789-241-8189'),
(43, 'Brian Bates', '383 Ortiz Extensions, West Stephanie, AS 71880', 'jaimejohnson@example.com', '+1-361-582-8513'),
(44, 'Angela Castro', '28506 Lisa Station, Bestport, AZ 02176', 'jonesjessica@example.com', '+1-430-679-6120'),
(45, 'Richard King', 'PSC 5036, Box 7601, APO AP 41248', 'onealmichael@example.com', '+1-886-345-1505'),
(46, 'Andrea Ramirez', '394 Barron Roads Apt. 914, Matthewville, IN 56568', 'katelynpearson@example.com', '+1-075-891-2278'),
(47, 'Brian Hughes', '433 Owens Fords, Port Erikberg, ID 40937', 'qramirez@example.com', '+1-226-128-4625'),
(48, 'Aaron Munoz', '38142 Heidi Plains, Leefurt, GU 63632', 'kathryndyer@example.com', '+1-281-206-5330'),
(49, 'Erin Coffey', '74782 Cox Crossroad, West Frederick, PR 55159', 'abbottcathy@example.com', '+1-187-456-0103'),
(50, 'Jesse Parker', 'PSC 6590, Box 0618, APO AE 61745', 'radams@example.com', '+1-739-420-4813'),
(51, 'Angela Buck', '6169 Edwards Center Apt. 600, West Bryceberg, HI 01127', 'qwoods@example.com', '+1-627-617-2779'),
(52, 'Jill Pitts', '664 Donald Rapid Suite 443, Destinybury, OR 84168', 'johnstrong@example.com', '+1-553-848-3717'),
(53, 'Zachary Acevedo', '245 Spencer Rue, South Amyberg, OK 94175', 'nelsonvincent@example.com', '+1-278-608-9103'),
(54, 'Walter Wolf', '84837 Ross Trace Suite 504, Hollowayton, WI 73700', 'stephen73@example.com', '+1-160-289-3250'),
(55, 'Norman Strickland', 'PSC 8065, Box 2885, APO AE 97759', 'cody97@example.com', '+1-128-496-4841'),
(56, 'Ashley Gonzalez', '232 Charles Forge, Port Christian, MD 60279', 'xtaylor@example.com', '+1-834-451-1296'),
(57, 'Jeffrey Rojas', '56086 Nicholson Plain, New Alyssa, KS 38713', 'hancockjames@example.com', '+1-493-931-5100'),
(58, 'Amy Pierce', '58582 Moyer Ports, Bennettshire, PA 55923', 'ledwards@example.com', '+1-667-304-4037'),
(59, 'Brian Mills', '285 Greene Street Suite 986, North Michael, AL 81449', 'joseph83@example.com', '+1-517-063-1714'),
(60, 'Karen Edwards', '4625 Franklin Mews Suite 220, Ingramshire, WV 87339', 'grayann@example.com', '+1-666-058-2850'),
(61, 'Sheila Patrick', '6773 Henry Garden Suite 859, Sandraton, SD 56866', 'reedjames@example.com', '+1-619-380-7917'),
(62, 'Maurice Williamson', '682 Ellis Villages, Port Elizabeth, KY 08176', 'linda97@example.com', '+1-013-510-9014'),
(63, 'Nicholas Evans', '57389 Castillo Divide, North Julieport, MN 40659', 'keith78@example.com', '+1-025-998-6662'),
(64, 'Daniel Mueller', '3931 Chen Way Suite 413, Brianaberg, NY 25209', 'ypowell@example.com', '+1-443-507-0752'),
(65, 'Thomas Cobb', '928 Anderson Throughway, Patelville, AZ 01634', 'smithtina@example.com', '+1-303-860-8438'),
(66, 'Sarah Lee', '842 Amy Square, Lake Linda, NY 81700', 'sarahgilbert@example.com', '+1-299-444-0451'),
(67, 'Justin Martin', '41563 Megan Mill, South Raymond, DE 84521', 'omartinez@example.com', '+1-761-826-6624'),
(68, 'Katherine Brown', '591 Rodriguez Green, New Jared, MI 85213', 'cheryl35@example.com', '+1-338-688-5970'),
(69, 'Shannon Kim', '9454 Juan Forge, Lake Andrew, VA 09452', 'danielfry@example.com', '+1-344-465-8020'),
(70, 'Kyle Goodwin', '101 Castillo Drive Apt. 794, Alexanderside, DE 49552', 'johntaylor@example.com', '+1-139-146-0847'),
(71, 'Amanda Bush', 'Unit 6805 Box 6032, DPO AP 52364', 'yspence@example.com', '+1-906-326-8546'),
(72, 'Sue Waller', '090 Matthew Cape Apt. 595, New Stephen, AL 84985', 'apayne@example.com', '+1-631-763-8732'),
(73, 'Chris Nunez', '8071 Abigail Camp, Lake Ryan, AL 43280', 'sandra96@example.com', '+1-912-669-6229'),
(74, 'Larry Long', '79323 Torres Flats, Philipbury, OH 02198', 'harry54@example.com', '+1-076-401-7526'),
(75, 'Catherine Young', '98245 Kevin Land, East Marcusstad, NM 79723', 'cabreramary@example.com', '+1-604-229-1349'),
(76, 'Stephanie Brown', '91962 Griffin Rapids, Lake Michael, OK 96808', 'batesryan@example.com', '+1-163-890-3711'),
(77, 'Christopher Anderson', '5076 Tina Ford, Spearsborough, MH 04003', 'jallen@example.com', '+1-704-284-8993'),
(78, 'Nicole Hammond', '56621 Sophia Centers, Vincentshire, KY 27469', 'masonpeter@example.com', '+1-873-230-4538'),
(79, 'Christopher Brooks', '361 Timothy Lodge Suite 186, South Nicholasport, AL 65211', 'antonio11@example.com', '+1-111-321-3965'),
(80, 'Robert Reid', '50390 Crystal Crescent Apt. 439, Lake Christopherborough, OH 65291', 'jgibbs@example.com', '+1-099-141-7696'),
(81, 'Rebekah Nicholson', '7830 Keller Estate Suite 900, New Anthony, MP 02186', 'chill@example.com', '+1-641-020-9305'),
(82, 'Michael Bryant', '3181 King Landing Apt. 978, North Caleb, FL 45309', 'mmcdonald@example.com', '+1-515-726-2807'),
(83, 'Mitchell Castaneda', '75253 Kaitlin Locks, Micheleville, MA 66890', 'troygarza@example.com', '+1-694-419-8189'),
(84, 'Kimberly Schroeder', '217 Melissa Vista Apt. 674, Lindsayview, AR 77248', 'blevinsryan@example.com', '+1-971-839-5187'),
(85, 'Shelby Medina', '48754 Leon Camp, Lake Justinbury, ID 30025', 'williamjohnson@example.com', '+1-007-946-2265'),
(86, 'Amy Lee', '36539 Eileen Run Suite 144, South Gail, OK 50944', 'donald21@example.com', '+1-953-524-6348'),
(87, 'Brandon Dalton', '777 Porter Roads Apt. 093, Christopherstad, PR 66988', 'rodriguezvictoria@example.com', '+1-467-242-9508'),
(88, 'Melissa Alvarez', 'Unit 7184 Box 4539, DPO AP 74291', 'robinsonjose@example.com', '+1-189-765-3417'),
(89, 'Samantha Roman', '7419 Perez Garden, Andreabury, AR 78413', 'philipandrews@example.com', '+1-560-131-1542'),
(90, 'Michael Harris', '57719 Webb Roads Apt. 520, Torresland, MP 27737', 'wendyduncan@example.com', '+1-724-397-4939'),
(91, 'Mark Carpenter', '7619 Patrick Lake Apt. 757, Alexandriaville, PA 30171', 'gtaylor@example.com', '+1-302-057-8647'),
(92, 'Ryan Murray', '047 Moore Prairie Apt. 075, Vickiehaven, AS 11039', 'mendozacameron@example.com', '+1-396-575-8327'),
(93, 'Dennis Mills', '1033 Carrie Vista Suite 553, Lopezfort, TN 49643', 'jbarnett@example.com', '+1-624-721-5396'),
(94, 'Mark Garza', '40581 Daniel Ville, Jamesburgh, DE 19755', 'janicetodd@example.com', '+1-831-800-4651'),
(95, 'Justin Ford', '187 Vazquez Plain Apt. 128, Port Autumnside, RI 80208', 'mooremichael@example.com', '+1-198-028-9050'),
(96, 'Dylan Watson', '30045 Brittany Ramp, Ellismouth, NM 83191', 'hallrobert@example.com', '+1-549-509-6444'),
(97, 'Betty Sandoval', '9574 Sandoval Tunnel Apt. 786, West Donna, SD 20724', 'shafferdebra@example.com', '+1-593-326-1696'),
(98, 'Brian Thompson', '5853 Aaron Inlet Suite 070, New Chelsea, VA 26013', 'anamejia@example.com', '+1-060-338-3351'),
(99, 'Rachel Higgins', '3696 Leslie Walks Suite 052, Amandaborough, OH 42662', 'daniel19@example.com', '+1-549-514-6169'),
(100, 'Johnny Velazquez', '26706 Keith Roads, East Heiditown, AK 17797', 'jennifer59@example.com', '+1-118-007-4411'),

INSERT INTO Suppliers (SupplierID, Name, ContactInfo, Rating) VALUES
(6, 'White Ltd', 'anthony57@example.com | +1-651-955-2597', 4.04),
(7, 'Hamilton LLC', 'amydowns@example.com | +1-778-994-4197', 3.92),
(8, 'Jacobs LLC', 'balvarez@example.com | +1-740-711-4482', 4.03),
(9, 'Hall, Wilkerson and Moore', 'jacquelineshea@example.com | +1-605-448-9938', 4.12),
(10, 'Rogers, Taylor and Byrd', 'danielyates@example.com | +1-895-069-7215', 4.28),
(11, 'Sandoval Group', 'pphillips@example.com | +1-913-932-2040', 3.8),
(12, 'Rivera, Gamble and Smith', 'ashleycarr@example.com | +1-739-275-7136', 4.54),

INSERT INTO Warehouses (WarehouseID, Location, Capacity) VALUES
(6, 'Wrightbury, VA', 9556.29),
(7, 'Jeffreymouth, WA', 7644.16),

INSERT INTO Products (ProductID, Name, Category, UnitPrice, SupplierID) VALUES
(6, 'While Model F', 'Electronics', 522.47, 11),
(7, 'American Model G', 'Electronics', 183.31, 2),
(8, 'American Model H', 'Hardware', 172.52, 8),
(9, 'Relate Model I', 'Groceries', 408.59, 2),
(10, 'Establish Model J', 'Groceries', 599.04, 4),
(11, 'Type Model K', 'Electronics', 141.77, 1),
(12, 'Although Model L', 'Hardware', 694.84, 5),
(13, 'Son Model M', 'Machinery', 183.34, 8),
(14, 'Attack Model N', 'Electronics', 672.31, 10),
(15, 'Social Model O', 'Hardware', 241.18, 5),
(16, 'Degree Model P', 'Furniture', 650.13, 2),
(17, 'Painting Model Q', 'Hardware', 934.91, 8),
(18, 'Wonder Model R', 'Furniture', 61.1, 7),
(19, 'Maybe Model S', 'Machinery', 330.12, 5),
(20, 'There Model T', 'Furniture', 180.09, 7),
(21, 'Level Model U', 'Furniture', 866.14, 6),
(22, 'Return Model V', 'Electronics', 979.11, 4),
(23, 'Civil Model W', 'Hardware', 656.19, 4),
(24, 'Between Model X', 'Groceries', 443.64, 3),
(25, 'Nature Model Y', 'Furniture', 364.28, 2),
(26, 'Determine Model Z', 'Furniture', 670.76, 2),
(27, 'Catch Model [', 'Hardware', 445.19, 7),
(28, 'Phone Model \', 'Electronics', 975.18, 6),
(29, 'Set Model ]', 'Hardware', 802.74, 4),
(30, 'Minute Model ^', 'Hardware', 802.11, 6),
(31, 'Article Model _', 'Hardware', 967.99, 9),
(32, 'Cultural Model `', 'Hardware', 168.73, 8),
(33, 'Design Model a', 'Furniture', 555.39, 1),
(34, 'Toward Model b', 'Electronics', 117.24, 3),
(35, 'Only Model c', 'Hardware', 779.75, 3),
(36, 'Industry Model d', 'Furniture', 80.04, 4),
(37, 'Doctor Model e', 'Machinery', 656.3, 12),
(38, 'Indeed Model f', 'Electronics', 854.94, 5),
(39, 'Third Model g', 'Hardware', 298.5, 12),
(40, 'Take Model h', 'Furniture', 61.54, 7),
(41, 'Movement Model i', 'Hardware', 189.72, 8),
(42, 'Ahead Model j', 'Furniture', 467.31, 11),
(43, 'Spring Model k', 'Electronics', 424.9, 9),
(44, 'Customer Model l', 'Furniture', 203.11, 4),
(45, 'Likely Model m', 'Groceries', 962.8, 1),
(46, 'Hear Model n', 'Furniture', 852.19, 12),
(47, 'Lead Model o', 'Machinery', 782.72, 11),
(48, 'Mean Model p', 'Groceries', 667.48, 8),
(49, 'Imagine Model q', 'Hardware', 315.02, 1),
(50, 'They Model r', 'Electronics', 171.58, 11),
(51, 'Kind Model s', 'Machinery', 603.77, 7),
(52, 'Similar Model t', 'Machinery', 932.42, 10),
(53, 'Watch Model u', 'Electronics', 313.64, 5),
(54, 'Rate Model v', 'Machinery', 995.37, 4),
(55, 'Away Model w', 'Groceries', 911.81, 12),
(56, 'Story Model x', 'Machinery', 252.49, 2),
(57, 'Together Model y', 'Electronics', 986.07, 5),
(58, 'Able Model z', 'Furniture', 666.97, 12),
(59, 'Anyone Model {', 'Electronics', 705.15, 7),
(60, 'Big Model |', 'Furniture', 146.28, 12),

INSERT INTO Orders (OrderID, CustomerID, OrderDate, TotalAmount) VALUES
(6, 90, '2024-07-23', 364.44),
(7, 26, '2023-12-30', 1240.27),
(8, 38, '2024-01-19', 1797.77),
(9, 27, '2023-11-27', 1392.2),
(10, 19, '2023-10-22', 539.46),
(11, 93, '2024-04-18', 1327.2),
(12, 76, '2024-07-20', 1260.06),
(13, 97, '2023-09-02', 639.8),
(14, 90, '2024-06-29', 1965.32),
(15, 35, '2023-12-27', 1461.53),
(16, 12, '2024-07-28', 504.1),
(17, 48, '2024-07-11', 1724.02),
(18, 39, '2024-06-01', 334.86),
(19, 73, '2023-10-05', 133.16),
(20, 31, '2023-10-22', 141.76),
(21, 29, '2024-08-22', 1970.62),
(22, 46, '2024-04-27', 1661.31),
(23, 98, '2024-03-01', 1150.16),
(24, 29, '2023-08-29', 1949.94),
(25, 54, '2024-05-06', 236.38),
(26, 91, '2023-09-26', 1663.23),
(27, 54, '2024-01-05', 1484.47),
(28, 99, '2024-03-28', 498.58),
(29, 22, '2024-03-07', 134.16),
(30, 43, '2024-03-27', 641.42),
(31, 22, '2024-01-06', 1464.68),
(32, 57, '2024-01-11', 1281.24),
(33, 9, '2023-11-30', 1365.1),
(34, 71, '2024-05-14', 1805.21),
(35, 31, '2023-10-01', 610.3),
(36, 55, '2024-06-26', 593.87),
(37, 89, '2024-07-17', 480.65),
(38, 84, '2024-03-26', 1227.9),
(39, 12, '2023-09-25', 1076.12),
(40, 3, '2023-10-05', 1314.56),
(41, 94, '2024-06-06', 1729.22),
(42, 31, '2023-12-15', 1808.91),
(43, 83, '2023-12-09', 366.23),
(44, 60, '2024-03-25', 1201.28),
(45, 46, '2024-07-12', 1025.86),
(46, 30, '2024-06-10', 940.12),
(47, 65, '2024-08-16', 1832.36),
(48, 1, '2024-03-19', 593.43),
(49, 38, '2024-08-11', 1382.47),
(50, 12, '2023-09-30', 1523.46),
(51, 25, '2024-05-13', 1843.31),
(52, 35, '2023-11-28', 411.02),
(53, 45, '2024-01-18', 145.48),
(54, 26, '2023-08-26', 1227.73),
(55, 14, '2024-02-18', 1862.58),
(56, 48, '2024-04-30', 1027.45),
(57, 3, '2024-07-03', 149.09),
(58, 45, '2024-08-03', 325.37),
(59, 69, '2024-06-16', 1166.25),
(60, 12, '2023-12-14', 1582.26),
(61, 86, '2024-03-08', 1694.18),
(62, 88, '2024-04-01', 272.31),
(63, 92, '2024-05-01', 1194.9),
(64, 53, '2024-06-04', 1025.55),
(65, 75, '2023-11-15', 476.56),
(66, 28, '2023-10-25', 103.5),
(67, 44, '2023-11-22', 1437.24),
(68, 28, '2023-09-21', 297.88),
(69, 13, '2024-05-14', 662.91),
(70, 85, '2024-04-29', 116.28),
(71, 93, '2023-09-17', 895.04),
(72, 44, '2023-10-07', 1532.16),
(73, 13, '2023-10-23', 221.45),
(74, 42, '2024-01-14', 1427.81),
(75, 14, '2024-07-20', 1422.04),
(76, 25, '2024-08-01', 1809.85),
(77, 76, '2024-07-14', 1853.4),
(78, 5, '2024-01-05', 1537.02),
(79, 93, '2024-04-24', 696.54),
(80, 5, '2024-05-09', 323.97),
(81, 18, '2024-04-17', 259.54),
(82, 89, '2023-11-04', 1325.28),
(83, 35, '2024-02-24', 1919.29),
(84, 57, '2024-02-25', 1830.38),
(85, 35, '2024-03-30', 1307.91),
(86, 1, '2024-08-04', 1416.61),
(87, 28, '2024-04-01', 1304.2),
(88, 41, '2023-12-02', 708.45),
(89, 47, '2024-01-07', 1428.76),
(90, 40, '2024-03-14', 1532.05),
(91, 80, '2024-06-17', 1224.28),
(92, 17, '2024-06-05', 1303.79),
(93, 14, '2024-02-21', 537.18),
(94, 83, '2024-04-12', 829.85),
(95, 29, '2023-11-23', 851.86),
(96, 61, '2023-11-30', 1434.52),
(97, 72, '2024-07-21', 659.17),
(98, 21, '2024-01-09', 1410.05),
(99, 4, '2024-03-13', 1239.66),
(100, 37, '2024-07-24', 378.38),
(101, 9, '2024-03-22', 508.5),
(102, 14, '2024-06-06', 1514.12),
(103, 3, '2024-08-02', 287.69),
(104, 43, '2024-01-28', 105.67),
(105, 96, '2024-07-06', 1995.36),
(106, 21, '2024-05-30', 889.73),
(107, 59, '2023-12-27', 1101.64),
(108, 85, '2024-07-18', 876.54),
(109, 38, '2024-07-13', 1351.09),
(110, 75, '2024-08-15', 1856.38),
(111, 33, '2023-10-29', 1682.95),
(112, 65, '2024-05-03', 1621.04),
(113, 77, '2024-03-24', 753.67),
(114, 56, '2024-01-25', 286.86),
(115, 85, '2023-12-02', 609.72),
(116, 37, '2023-11-12', 1797.98),
(117, 32, '2024-05-21', 914.02),
(118, 88, '2023-11-23', 796.4),
(119, 79, '2024-06-06', 338.94),
(120, 77, '2023-10-18', 1602.7),
(121, 26, '2024-06-29', 1398.37),
(122, 13, '2024-02-03', 1629.25),
(123, 46, '2024-01-09', 1423.15),
(124, 35, '2024-06-02', 820.46),
(125, 86, '2024-08-15', 1185.42),
(126, 42, '2023-10-31', 1293.13),
(127, 17, '2024-04-03', 1212.43),
(128, 9, '2023-12-23', 548.64),
(129, 83, '2024-01-17', 1392.36),
(130, 53, '2024-01-13', 661.06),
(131, 84, '2023-09-11', 461.44),
(132, 50, '2024-08-23', 1192.43),
(133, 94, '2024-06-08', 150.86),
(134, 4, '2024-02-12', 875.96),
(135, 66, '2024-05-25', 136.02),
(136, 82, '2024-01-12', 1947.62),
(137, 85, '2023-11-09', 449.41),
(138, 66, '2024-04-15', 507.55),
(139, 59, '2023-08-27', 1859.09),
(140, 32, '2024-02-22', 1219.53),
(141, 88, '2023-11-04', 155.42),
(142, 4, '2023-09-14', 898.73),
(143, 89, '2023-12-26', 755.64),
(144, 45, '2023-11-08', 1267.39),
(145, 10, '2023-12-19', 1563.91),
(146, 51, '2023-11-30', 583.85),
(147, 12, '2023-10-09', 754.6),
(148, 82, '2024-01-15', 1327.44),
(149, 52, '2024-04-25', 381.05),
(150, 53, '2024-07-11', 136.5),
(151, 18, '2023-09-06', 1094.18),
(152, 33, '2023-10-20', 684.81),
(153, 6, '2024-03-03', 1196.12),
(154, 11, '2024-06-30', 1423.95),
(155, 94, '2023-10-17', 737.82),
(156, 24, '2024-05-16', 993.3),
(157, 67, '2023-10-31', 1061.67),
(158, 1, '2024-02-17', 1383.37),
(159, 5, '2024-08-24', 1295.97),
(160, 64, '2023-10-23', 1947.45),
(161, 22, '2024-06-27', 587.02),
(162, 1, '2023-09-07', 273.28),
(163, 42, '2024-07-25', 829.73),
(164, 6, '2024-02-17', 168.58),
(165, 59, '2023-10-23', 989.4),
(166, 93, '2024-06-16', 1248.59),
(167, 100, '2024-02-12', 939.48),